/**
 * @foundry/core build script
 *
 * Generates dist/tokens.css from the color engine.
 *
 * Usage:
 *   npx tsx scripts/build.ts
 *   npx tsx scripts/build.ts --accent #8b5cf6
 *   npx tsx scripts/build.ts --accent #8b5cf6 --harmony 0.15
 *
 * Output:
 *   dist/tokens.css — CSS custom properties for light + dark themes
 *
 * This file is the bridge between @foundry/core (TypeScript engine)
 * and any framework that consumes design tokens (Angular, Vue, etc.)
 * The generated CSS works in any browser without any build tool.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { generateSemanticTokens, generateThemeCSS, validateHex } from '../src/index.js';

// ─── Configuration ───────────────────────────────────────

const DEFAULT_ACCENT = '#3a5afe';
const DEFAULT_HARMONY = 0.12;

// Parse command line arguments
// e.g. npx tsx scripts/build.ts --accent #8b5cf6 --harmony 0.15
const args = process.argv.slice(2);
const accentIndex = args.indexOf('--accent');
const harmonyIndex = args.indexOf('--harmony');

const accentColor = accentIndex !== -1
  ? (args[accentIndex + 1] ?? DEFAULT_ACCENT)
  : DEFAULT_ACCENT;

const harmonyStrength = harmonyIndex !== -1
  ? parseFloat(args[harmonyIndex + 1] ?? String(DEFAULT_HARMONY))
  : DEFAULT_HARMONY;

// ─── Validate inputs ─────────────────────────────────────

const validation = validateHex(accentColor);
if (!validation.valid) {
  console.error(`❌ Invalid accent color: ${validation.error}`);
  process.exit(1);
}

// ─── Generate tokens ─────────────────────────────────────

console.log(`🎨 Generating tokens...`);
console.log(`   Accent color:    ${accentColor}`);
console.log(`   Harmony strength: ${harmonyStrength}`);

const tokens = generateSemanticTokens({
  accentColor: validation.value ?? accentColor,
  harmonyStrength,
});

const { combined } = generateThemeCSS(tokens);

// ─── Write output ────────────────────────────────────────

// Get the directory of this script file
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Output to dist/tokens.css
const distDir = resolve(__dirname, '../dist');
const outputPath = resolve(distDir, 'tokens.css');

// Create dist/ folder if it doesn't exist
mkdirSync(distDir, { recursive: true });

// Add a header comment to the generated file
const header = `/**
 * Foundry Design Tokens
 * Generated by @foundry/core
 *
 * Accent color: ${accentColor}
 * Harmony strength: ${harmonyStrength}
 * Generated: ${new Date().toISOString()}
 *
 * Usage:
 *   <link rel="stylesheet" href="tokens.css">
 *   or
 *   @import 'tokens.css';
 *
 * Then use CSS custom properties in your styles:
 *   color: var(--color-primary-fill);
 *   background: var(--color-neutral-background);
 */

`;

writeFileSync(outputPath, header + combined, 'utf-8');

console.log(`✅ Tokens written to: ${outputPath}`);
console.log(`   Light theme: :root { ... }`);
console.log(`   Dark theme:  [data-theme="dark"] { ... }`);
