import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  generateSemanticTokens,
  generateThemeCSS,
  validateHex,
} from "../src/index.js";

const DEFAULT_ACCENT = "#3a5afe";
const DEFAULT_HARMONY = 0.12;

const args = process.argv.slice(2);
const accentIndex = args.indexOf("--accent");
const harmonyIndex = args.indexOf("--harmony");

const accentColor =
  accentIndex !== -1 ?
    (args[accentIndex + 1] ?? DEFAULT_ACCENT)
  : DEFAULT_ACCENT;

const harmonyStrength =
  harmonyIndex !== -1 ?
    parseFloat(args[harmonyIndex + 1] ?? String(DEFAULT_HARMONY))
  : DEFAULT_HARMONY;

const validation = validateHex(accentColor);
if (!validation.valid) {
  console.error(`❌ Invalid accent color: ${validation.error}`);
  process.exit(1);
}

console.log(`🎨 Generating tokens...`);
console.log(`   Accent color:     ${accentColor}`);
console.log(`   Harmony strength: ${harmonyStrength}`);

const tokens = generateSemanticTokens({
  accentColor: validation.value ?? accentColor,
  harmonyStrength,
});

const { combined } = generateThemeCSS(tokens);

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const distDir = resolve(__dirname, "../dist");
const outputPath = resolve(distDir, "tokens.css");

mkdirSync(distDir, { recursive: true });

const header = `/**
 * Foundry Design Tokens
 * Generated by @foundry/core
 * Accent color: ${accentColor}
 * Generated: ${new Date().toISOString()}
 */\n\n`;

writeFileSync(outputPath, header + combined, "utf-8");

console.log(`✅ Tokens written to: ${outputPath}`);
