/**
 * CSS Custom Properties Exporter
 *
 * Converts semantic token objects into CSS custom properties.
 *
 * Why CSS custom properties?
 * They are the universal format. Every framework reads them:
 * - Vanilla CSS uses them directly
 * - Tailwind v4 reads them via @theme
 * - React reads them via style={{ color: 'var(--color-primary-fill)' }}
 * - Figma Variables can be mapped to them
 *
 * Output example:
 * :root {
 *   --color-primary-fill: #3a5afe;
 *   --color-primary-text: #1a2fa8;
 *   --color-neutral-background: #f8fafc;
 * }
 *
 * Dark mode output uses [data-theme="dark"] selector:
 * [data-theme="dark"] {
 *   --color-primary-fill: #5b7aff;
 *   --color-neutral-background: #0f172a;
 * }
 *
 * This means dark mode works by setting data-theme="dark"
 * on the <html> element — no JavaScript class toggling needed.
 */

import {
  type SemanticTokenSet,
  type SemanticColorToken,
  type NeutralTokenScale,
} from '../semantic/tokens';
 import { getContrastRatio } from '../formula/contrast';

// ─── Types ───────────────────────────────────────────────

/**
 * The CSS output for both light and dark themes.
 */
export interface ThemeCSS {
  /** Full CSS string for light mode — goes in :root */
  light: string;
  /** Full CSS string for dark mode — goes in [data-theme="dark"] */
  dark: string;
  /** Both combined into one CSS string ready to inject or write to file */
  combined: string;
}

// ─── Helpers ─────────────────────────────────────────────

/**
 * Chooses white or black for text on top of a filled element.
 * Duplicated from tokens.ts intentionally — css-exporter should
 * not depend on tokens.ts internals, only its public types.
 */
const getContrastText = (fillHex: string): string => {
  const whiteContrast = getContrastRatio('#ffffff', fillHex);
  const blackContrast = getContrastRatio('#000000', fillHex);
  return whiteContrast >= blackContrast ? '#ffffff' : '#000000';
};

/**
 * Converts a camelCase property name to a CSS custom property name.
 *
 * Examples:
 * 'fillHover'   → '--color-primary-fill-hover'
 * 'bgHover'     → '--color-primary-bg-hover'
 * 'contrastText'→ '--color-primary-contrast-text'
 * 'textStrong'  → '--color-neutral-text-strong'
 */
const toCustomProperty = (
  tokenGroup: string,
  propertyName: string
): string => {
  const kebab = propertyName.replace(
    /([A-Z])/g,
    match => `-${match.toLowerCase()}`
  );
  return `--color-${tokenGroup}-${kebab}`;
};

/**
 * Converts a semantic action color token to CSS custom properties.
 *
 * e.g. tokenToCSSProperties('primary', primaryToken)
 * →
 * --color-primary-bg: #eef1ff;
 * --color-primary-bg-hover: #dde6ff;
 * --color-primary-fill: #3a5afe;
 * ...
 */
const actionTokenToCSSProperties = (
  groupName: string,
  token: SemanticColorToken
): string => {
  const properties: Record<string, string> = {
    bg:           token.bg,
    bgHover:      token.bgHover,
    border:       token.border,
    borderHover:  token.borderHover,
    fill:         token.fill,
    fillHover:    token.fillHover,
    fillActive:   token.fillActive,
    text:         token.text,
    textHover:    token.textHover,
    textActive:   token.textActive,
    contrastText: token.contrastText,
  };

  return Object.entries(properties)
    .map(([key, value]) => `  ${toCustomProperty(groupName, key)}: ${value};`)
    .join('\n');
};

/**
 * Converts the neutral scale to CSS custom properties.
 */
const neutralToCSSProperties = (token: NeutralTokenScale): string => {
  const properties: Record<string, string> = {
    background:   token.background,
    surface:      token.surface,
    surfaceHover: token.surfaceHover,
    border:       token.border,
    borderStrong: token.borderStrong,
    textMuted:    token.textMuted,
    text:         token.text,
    textStrong:   token.textStrong,
  };

  return Object.entries(properties)
    .map(([key, value]) => `  ${toCustomProperty('neutral', key)}: ${value};`)
    .join('\n');
};

// ─── Light Theme ─────────────────────────────────────────

/**
 * Generates the light theme CSS block.
 *
 * Uses :root selector so tokens are available everywhere
 * by default without any extra setup.
 */
export const generateLightThemeCSS = (tokens: SemanticTokenSet): string => {
  const lines = [
    '/**',
    ' * Light theme — generated by @foundry/core',
    ' * Do not edit manually. Re-generate with: yarn build:tokens',
    ' */',
    ':root {',
    actionTokenToCSSProperties('primary', tokens.primary),
    '',
    actionTokenToCSSProperties('success', tokens.success),
    '',
    actionTokenToCSSProperties('warning', tokens.warning),
    '',
    actionTokenToCSSProperties('error', tokens.error),
    '',
    actionTokenToCSSProperties('info', tokens.info),
    '',
    neutralToCSSProperties(tokens.neutral),
    '}',
  ];

  return lines.join('\n');
};

// ─── Dark Theme ──────────────────────────────────────────

/**
 * Generates the dark theme CSS block.
 *
 * Dark mode strategy:
 * - Fill colors stay similar but slightly lighter for contrast
 * - Background and surface colors become very dark
 * - Text colors invert (light text on dark backgrounds)
 * - Borders become more subtle
 *
 * We use the SAME token names as light mode — components
 * don't change. Only the values change.
 *
 * Activated by: <html data-theme="dark">
 *
 * Note: this is a starting point. A production dark theme
 * needs careful per-token tuning. The palette inversion
 * here is a principled approximation — not a final answer.
 */
export const generateDarkThemeCSS = (tokens: SemanticTokenSet): string => {
  /**
   * For dark mode we remap shades from each palette.
   * Light mode uses shade 1 (lightest) for bg.
   * Dark mode uses shade 10 or 11 for bg instead.
   *
   * The inversion logic:
   * shade N in light mode → shade (12 - N) in dark mode
   * e.g. shade 1 (97% lightness) → shade 11 (12% lightness)
   *      shade 6 stays near 6 but slightly adjusted
   */
  const invertShade = (shadeNumber: number): number => {
    return Math.min(11, Math.max(1, 12 - shadeNumber));
  };

  const actionTokenToDarkCSS = (
  groupName: string,
  token: SemanticColorToken
): string => {
  const palette = token.palette;
  const getHex = (n: number) =>
    palette.shades.find(s => s.shade === n)?.hex ?? token.fill;

  const darkFill = getHex(6);

  const darkProperties: Record<string, string> = {
    bg:           getHex(invertShade(1)),
    bgHover:      getHex(invertShade(2)),
    border:       getHex(invertShade(3)),
    borderHover:  getHex(invertShade(4)),
    fill:         darkFill,
    fillHover:    getHex(5),
    fillActive:   getHex(7),
    text:         getHex(invertShade(8)),
    textHover:    getHex(invertShade(7)),
    textActive:   getHex(invertShade(9)),
    // Recalculated for dark mode fill in case it changed
    contrastText: getContrastText(darkFill),
  };

  return Object.entries(darkProperties)
    .map(([key, value]) => `  ${toCustomProperty(groupName, key)}: ${value};`)
    .join('\n');
};

  const neutralToDarkCSS = (token: NeutralTokenScale): string => {
    const palette = token.palette;
    const getHex = (n: number) =>
      palette.shades.find(s => s.shade === n)?.hex ?? token.text;

    const darkProperties: Record<string, string> = {
      background:   getHex(11),
      surface:      getHex(10),
      surfaceHover: getHex(9),
      border:       getHex(8),
      borderStrong: getHex(7),
      textMuted:    getHex(4),
      text:         getHex(2),
      textStrong:   getHex(1),
    };

    return Object.entries(darkProperties)
      .map(([key, value]) => `  ${toCustomProperty('neutral', key)}: ${value};`)
      .join('\n');
  };

  const lines = [
    '/**',
    ' * Dark theme — generated by @foundry/core',
    ' * Activated by: <html data-theme="dark">',
    ' */',
    '[data-theme="dark"] {',
    actionTokenToDarkCSS('primary', tokens.primary),
    '',
    actionTokenToDarkCSS('success', tokens.success),
    '',
    actionTokenToDarkCSS('warning', tokens.warning),
    '',
    actionTokenToDarkCSS('error', tokens.error),
    '',
    actionTokenToDarkCSS('info', tokens.info),
    '',
    neutralToDarkCSS(tokens.neutral),
    '}',
  ];

  return lines.join('\n');
};

// ─── Combined Exporter ───────────────────────────────────

/**
 * Generates both light and dark theme CSS combined.
 *
 * This is the main function the web app and CLI will call.
 * The output can be:
 * - Written to a tokens.css file
 * - Injected into a <style> tag
 * - Copied by the user from the export panel
 */
export const generateThemeCSS = (tokens: SemanticTokenSet): ThemeCSS => {
  const light = generateLightThemeCSS(tokens);
  const dark = generateDarkThemeCSS(tokens);
  const combined = `${light}\n\n${dark}`;

  return { light, dark, combined };
};